"""4063 (EW lane) -- 4054's named target: a 4D structure with z = 12 and NO improper symmetry.

THEOREM (Steinberg, applied). For a finite reflection group W on R^n the stabiliser of any point p is
generated by the reflections that fix p. For W = H4 on R^4:
  (a) p on at least one mirror  =>  Stab(p) contains a reflection  =>  H4.p = H4+.p  =>  ACHIRAL orbit.
      Every 600-cell vertex, edge midpoint, face centre and cell centre lies on a mirror. This is why 4051,
      4053 ("left-icosian orbit = the 600-cell") and 4054 failed: every H4+-orbit of a SPECIAL point is a
      copy of an achiral H4-orbit.
  (b) p on no mirror  =>  Stab(p) trivial  =>  the 14400-point H4-orbit splits into TWO H4+-orbits of 7200,
      mirror images of each other; each is CHIRAL. Any isometry preserving the 600-cell lies in H4, so the
      check below over all 7200 improper elements is EXHAUSTIVE.
  Corollary: the smallest chiral H4+-invariant point set in R^4 has 7200 points per shell. Minimal, forced.

CONSTRUCTION (4D analogue of 4041's icosahedron + generic I-orbit):
  U = 600-cell (120 vertices, radius 1)  UNION  generic H4+-orbit O_p (7200 points, radius R = 1.7).
  R - 1 = 0.7 > 1/phi = 0.618, so every core vertex keeps EXACTLY its 12 edge-neighbours as first shell
  (the nearest decoration point is at 0.82), and those 12 lie in an affine 3-flat (icosahedral vertex figure).
CHECKS
  C1  |H4| = 14400 from closure of the 60 root reflections; |H4+| = 7200.
  C2  generic p: orbit has 7200 distinct points; ZERO improper elements map it to itself.
  C3  CONTROLS: p a vertex / an edge midpoint (on mirrors): orbit preserved by improper elements.
  C4  every core vertex of U: first shell = 12 points at 1/phi whose affine span is a 3-flat.
  C5  pseudoscalar chi(O) = sum_q sum_{unordered triples a,b,c in a SHELL-COMPLETE neighbourhood of q}
      det[q, a-q, b-q, c-q]: invariant under proper isometries, flips sign exactly under a reflection,
      nonzero for the generic orbit, exactly zero for the mirror-point control. (A "3 nearest" rule is not
      well defined on a degenerate shell -- the 4040 tie-break trap -- so the cutoff is placed in a gap.)
"""
import numpy as np, itertools
phi = (1 + 5 ** .5) / 2
rng = np.random.default_rng(4063)

def build600():
    Vs = []
    for i in range(4):
        for s in (1, -1):
            v = np.zeros(4); v[i] = s; Vs.append(v)
    for s in range(16): Vs.append(np.array([((s >> k) & 1) * 2 - 1 for k in range(4)]) / 2.0)
    b = [phi / 2, 1 / 2, 1 / (2 * phi), 0]
    for s1, s2, s3 in itertools.product((1, -1), repeat=3):
        sg = [b[0] * s1, b[1] * s2, b[2] * s3, b[3]]
        for pm in itertools.permutations(range(4)):
            if sum(1 for i in range(4) for j in range(i + 1, 4) if pm[i] > pm[j]) % 2 == 0:
                Vs.append(np.array([sg[pm[i]] for i in range(4)]))
    U = []
    for v in Vs:
        if not any(np.allclose(v, u, atol=1e-9) for u in U): U.append(v)
    return np.array(U)

V = build600(); N = len(V); assert N == 120
em = 1 / phi
D = np.linalg.norm(V[:, None] - V[None], axis=2)
E = [(i, j) for i in range(N) for j in range(i + 1, N) if abs(D[i, j] - em) < 1e-9]; assert len(E) == 720

# C1
key = lambda M: tuple(np.round(M, 8).ravel())
gens, axes = [], set()
for v in V:
    a = tuple(np.round(v * np.sign(v[np.flatnonzero(np.round(v, 8))[0]]), 8))
    if a in axes: continue
    axes.add(a); gens.append(np.eye(4) - 2 * np.outer(v, v))
G = {key(np.eye(4)): np.eye(4)}; frontier = [np.eye(4)]
while frontier:
    new = []
    for g in frontier:
        for s in gens:
            h = g @ s; k = key(h)
            if k not in G: G[k] = h; new.append(h)
    frontier = new
H4 = list(G.values()); dets = np.array([round(np.linalg.det(g)) for g in H4])
Hp = [g for g, d in zip(H4, dets) if d == 1]; Hm = [g for g, d in zip(H4, dets) if d == -1]
print(f"C1  |H4| = {len(H4)}  rotations {len(Hp)}  improper {len(Hm)}  (root reflections {len(gens)})")
assert len(H4) == 14400 and len(Hp) == 7200

def orbit(p):
    pts = {}
    for g in Hp:
        q = g @ p; pts.setdefault(tuple(np.round(q, 7)), q)
    return pts

def improper_preservers(pts, p):
    keys = set(pts.keys()); hits = 0
    for g in Hm:
        if tuple(np.round(g @ p, 7)) not in keys: continue          # fast reject on one image
        if all(tuple(np.round(g @ q, 7)) in keys for q in pts.values()): hits += 1
    return hits

def pseudoscalar(pts, kmin=6):
    P = np.array(list(pts.values())); n = len(P); tot = 0.0
    for i in range(n):
        d = np.linalg.norm(P - P[i], axis=1); d[i] = np.inf
        o = np.argsort(d); k = kmin
        while k < n - 1 and d[o[k]] - d[o[k - 1]] < 1e-6: k += 1       # extend cutoff to a gap
        for a, b, c in itertools.combinations(o[:k], 3):
            tot += np.linalg.det(np.array([P[i], P[a] - P[i], P[b] - P[i], P[c] - P[i]]))
    return tot

R = 1.7
p = rng.normal(size=4); p = R * p / np.linalg.norm(p)
O = orbit(p)
hits = improper_preservers(O, p)
print(f"C2  generic p: orbit size {len(O)}; improper elements preserving it: {hits}  (exhaustive over {len(Hm)})")
assert len(O) == 7200 and hits == 0

for lab, pc in [("vertex", R * V[0]),
                ("edge midpoint", R * (V[E[0][0]] + V[E[0][1]]) / np.linalg.norm(V[E[0][0]] + V[E[0][1]]))]:
    Oc = orbit(pc); hc = improper_preservers(Oc, pc)
    print(f"C3  control p on a mirror ({lab}): orbit size {len(Oc)}; improper preservers {hc}")
    assert hc > 0

P_all = np.vstack([V, np.array(list(O.values()))])
ok = True; dmin_dec = np.inf
for i in range(N):
    d = np.linalg.norm(P_all - V[i], axis=1); d[i] = np.inf
    dmin = d.min(); shell = np.flatnonzero(np.abs(d - dmin) < 1e-9)
    S = P_all[shell]; rank = np.linalg.matrix_rank(S[1:] - S[0], tol=1e-9)
    ok &= (len(shell) == 12 and abs(dmin - em) < 1e-9 and rank == 3)
    dmin_dec = min(dmin_dec, d[N:].min())
print(f"C4  every core vertex: first shell = 12 at 1/phi, affine span a 3-flat: {ok}; nearest decoration {dmin_dec:.4f}")
assert ok

chi = pseudoscalar(O)
Om = {tuple(np.round(q * np.array([1, 1, 1, -1]), 7)): q * np.array([1, 1, 1, -1]) for q in O.values()}
chi_m = pseudoscalar(Om)
chi_c = pseudoscalar(orbit(R * V[0]))
print(f"C5  chi(O) = {chi:+.6e}; mirror image {chi_m:+.6e}; sum {chi + chi_m:+.1e}; mirror-point control {chi_c:+.1e}")
assert abs(chi) > 1e-6 and abs(chi + chi_m) < 1e-9 and abs(chi_c) < 1e-9
print("C1-C5 PASS: a chiral 4D structure with z = 12 exists at cluster scale; 7200 per shell is the minimum.")
